[phases.setup]
nixPkgs = ["nodejs_18", "python311"]

[phases.install]
cmds = ["npm ci", "pip install -r python/requirements.txt"]

[phases.build]
cmds = ["npm run postinstall || true"]

[start]
cmd = "node server.js"
